### ISSUE TITLE
Using readOnly or writeOnly generate exception upon validation

### ISSUE THREAD

**Issue by rafael-org** [byu-oit/openapi-enforcer#109]
Since version 1.12.6 I get error messages like:
```
     TypeError: Cannot read property 'writeOnly' of undefined
      at schema.required.schema.required.filter.name (node_modules/openapi-enforcer/src/schema/validate.js:153:67)
```
```
     TypeError: Cannot read property 'readOnly' of undefined
      at schema.required.schema.required.filter.name (node_modules/openapi-enforcer/src/schema/validate.js:152:68)
```
I am able to make it work by changing:
```
if (options.readWriteMode === 'write' && !prop.readOnly) return true
if (options.readWriteMode === 'read' && !prop.writeOnly) return true
```
To something like:
```
if (options.readWriteMode === 'write' && prop && !prop.readOnly) return true
if (options.readWriteMode === 'read' && prop && !prop.writeOnly) return true
```

**Comment by Gi60s** [comment]
Thanks for the fix. I've published this with version `1.13.2`.
